Controllers/LocadoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HabitAqui.Data;

namespace HabitAqui.Controllers
{
    public class LocadoresController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LocadoresController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Locadores
        public async Task<IActionResult> Index()
        {
              return _context.locadores != null ? 
                          View(await _context.locadores.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.locadores'  is null.");
        }

        // GET: Locadores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.locadores == null)
            {
                return NotFound();
            }

            var locador = await _context.locadores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (locador == null)
            {
                return NotFound();
            }

            return View(locador);
        }

        // GET: Locadores/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Locadores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,EstadoSubscricao")] Locador locador)
        {
            if (ModelState.IsValid)
            {
                _context.Add(locador);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(locador);
        }

        // GET: Locadores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.locadores == null)
            {
                return NotFound();
            }

            var locador = await _context.locadores.FindAsync(id);
            if (locador == null)
            {
                return NotFound();
            }
            return View(locador);
        }

        // POST: Locadores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,EstadoSubscricao")] Locador locador)
        {
            if (id != locador.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(locador);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LocadorExists(locador.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(locador);
        }

        // GET: Locadores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.locadores == null)
            {
                return NotFound();
            }

            var locador = await _context.locadores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (locador == null)
            {
                return NotFound();
            }

            return View(locador);
        }

        // POST: Locadores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.locadores == null)
            {
                return Problem("Entity set 'ApplicationDbContext.locadores'  is null.");
            }
            var locador = await _context.locadores.FindAsync(id);
            if (locador != null)
            {
                _context.locadores.Remove(locador);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LocadorExists(int id)
        {
          return (_context.locadores?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Admin/Admin.cshtml
@{
    ViewData["Title"] = "Administração";
}
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
}
<div class="container mt-4">
    <h1>Bem-vindo, administrador.</h1>

    <h4 class="mt-4">Gestão dos locadores:</h4>
    <div class="mb-3">
        <a class="btn btn-primary" asp-area="" asp-controller="Admin" asp-action="ListaLoc">Listar Locadores</a>
        <a class="btn btn-success" asp-area="" asp-controller="Admin" asp-action="CreateLoc">Criar Locador</a>
    </div>

    <h4 class="mt-4">Gestão das categorias de habitações:</h4>
    <div class="mb-3">
        <a class="btn btn-primary" asp-area="" asp-controller="Admin" asp-action="ListaCat">Listar Categorias de Habitações</a>
        <a class="btn btn-success" asp-area="" asp-controller="Admin" asp-action="CreateCat">Criar Categoria de Habitações</a>
    </div>

    <h4 class="mt-4">Gestão dos utilizadores:</h4>
    <div class="mb-3">
        <a class="btn btn-primary" asp-area="" asp-controller="Admin" asp-action="ListaUsr">Listar Utilizadores</a>
    </div>
</div>

Views/Admin/CreateCat.cshtml
@model HabitAqui.Data.CategoriaHabitacao

@{
    ViewData["Title"] = "Adicionar Categoria de Habitção";
}

<h2 class="mb-4">Adicionar Categoria de Habitação</h2>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="CreateCat" class="form-horizontal">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="NomeCategoria" class="control-label col-md-4">Nome da Categoria:</label>
                <div class="col-md-8">
                    <input asp-for="NomeCategoria" class="form-control" />
                    <span asp-validation-for="NomeCategoria" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="ativo" /> @Html.DisplayNameFor(model => model.ativo)
                </label>
            </div>
            </p>
            <div class="btn-group">
                <button type="submit" class="btn btn-success">Criar</button>
                <a asp-area="" asp-controller="Admin" asp-action="Admin" class="btn btn-secondary">Voltar</a>
            </div>

        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Admin/CreateLoc.cshtml
@model HabitAqui.Data.Locador

@{
    ViewData["Title"] = "Adicionar Locador";
}

<h2 class="mb-4">Adicionar Locador</h2>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="CreateLoc" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label">Nome:</label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" asp-for="EstadoSubscricao" />
                <label class="form-check-label" for="EstadoSubscricao">@Html.DisplayNameFor(model => model.EstadoSubscricao)</label>
            </div>
            </p>
            <div class="btn-group">
                <button type="submit" class="btn btn-success">Criar</button>
                <a asp-area="" asp-controller="Admin" asp-action="Admin" class="btn btn-secondary">Voltar</a>

            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Admin/DeleteCat.cshtml
@model HabitAqui.Data.CategoriaHabitacao

@{
    ViewData["Title"] = "Eliminar Categoria de Habitação";
}

<h2 class="mb-4">Eliminar Categoria de Habitação</h2>

<h5 class="mb-2">Tem certeza de que deseja eliminar?</h5>

<div class="row">
    <hr />
    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.NomeCategoria)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.NomeCategoria)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ativo)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ativo)
            </dd>
        </dl>
    </div>
</div>

<form asp-action="DeleteCat">
    <input type="hidden" asp-for="Id" />

    <div class="btn-group">
        <button type="submit" class="btn btn-danger">Eliminar</button>
        <a asp-action="ListaCat" class="btn btn-secondary">Voltar</a>
    </div>

</form>

Views/Admin/DeleteLoc.cshtml
@model HabitAqui.Data.Locador

@{
    ViewData["Title"] = "Eliminar Locador";
}

<h2 class="mb-4">Eliminar locador</h2>

<h5 class="mb-2">Tem a certeza que deseja eliminar?</h5>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EstadoSubscricao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EstadoSubscricao)
        </dd>
    </dl>

    <form asp-action="DeleteLoc" method="post">
        <input type="hidden" asp-for="Id" />
        
        <div class="btn-group">
        <button type="submit" class="btn btn-danger">Eliminar</button>
        <a asp-action="ListaLoc" class="btn btn-secondary">Voltar</a>
        </div>
    </form>
</div>

Views/Admin/DetailsCat.cshtml
@model HabitAqui.Data.CategoriaHabitacao

@{
    ViewData["Title"] = "Detalhes da Categoria de Habitação";
}

<h2 class="mb-4">Detalhes da Categoria de Habitação</h2>
</hr>
<div class="row">
    <div class="col-md-6">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.NomeCategoria)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.NomeCategoria)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ativo)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ativo)
            </dd>
        </dl>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="btn-group">
            <a asp-action="EditCat" asp-route-id="@Model?.Id" class="btn btn-primary">Editar</a>
            <a asp-action="ListaCat" class="btn btn-secondary">Voltar</a>
        </div>
    </div>
</div>

Views/Admin/EditCat.cshtml
@model HabitAqui.Data.CategoriaHabitacao

@{
    ViewData["Title"] = "Editar Categoria de Habitação";
}

<h2 class="mb-4">Editar categoria de habitação</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditCat">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="NomeCategoria" class="control-label"></label>
                <input asp-for="NomeCategoria" class="form-control" />
                <span asp-validation-for="NomeCategoria" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="ativo" /> @Html.DisplayNameFor(model => model.ativo)
                </label>
            </div>
            </p>
            <div class="btn-group">
                <input type="submit" value="Editar" class="btn btn-primary" />
                <a asp-action="ListaCat" class="btn btn-secondary">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Admin/EditLoc.cshtml
@model HabitAqui.Data.Locador

@{
    ViewData["Title"] = "Editar Locador";
}

<h2 class="mb-4">Editar Locador</h2>

<div class="row">
    <div class="col-md-6">
        <form asp-action="EditLoc" method="post" class="needs-validation" novalidate>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />

            <div class="form-group">
                <label asp-for="Nome" class="control-label">Nome:</label>
                <input asp-for="Nome" class="form-control" required />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>

            <div class="form-check mb-3">
                <input class="form-check-input" asp-for="EstadoSubscricao" />
                <label class="form-check-label" for="EstadoSubscricao">@Html.DisplayNameFor(model => model.EstadoSubscricao)</label>
            </div>
            </p>
            <div class="btn-group">
                <button type="submit" class="btn btn-primary">Guardar</button>
                <a asp-action="ListaLoc" class="btn btn-secondary">Voltar</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Admin/EditUsr.cshtml
@model UserViewModel
@using Microsoft.AspNetCore.Identity

@{
    ViewData["Title"] = "Editar Utilizador";
}

<h2 class="mb-4">Editar Utilizador</h2>

@if (Model != null)
{
    <form asp-action="GuardarEdicao" asp-route-id="@Model.IdUser" method="post" class="needs-validation" novalidate>

        <div class="form-group">
            <label for="UserName">Nome de Utilizador:</label>
            <input asp-for="UserName" class="form-control" required />
            <div class="invalid-feedback">Por favor, insira um nome de utilizador.</div>
        </div>

        <div class="form-group">
            <label for="Email">Email:</label>
            <input asp-for="Email" class="form-control" required />
            <div class="invalid-feedback">Por favor, insira um endereço de email válido.</div>
        </div>

        <div class="form-group">
            <label for="PhoneNumber">Número de Telemóvel:</label>
            <input asp-for="PhoneNumber" class="form-control" />
            <div class="invalid-feedback">Por favor, insira um número de telemóvel válido.</div>
        </div>

        <div class="form-group">
            <label for="Roles">Funções:</label>

            @foreach (var role in ViewBag.AllRoles)
            {
                @if (role == "funcionario") continue;

                var isChecked = Model.Roles.Contains(role);
                <div class="form-check">
                    <input type="checkbox" name="Roles" value="@role" class="form-check-input" @(isChecked ? "checked" : "") />
                    <label class="form-check-label">@role</label>
                </div>
            }
            <input type="hidden" asp-for="Roles" />
        </div>

        <div class="mt-3">
            <button type="submit" class="btn btn-primary mr-2">Guardar</button>
            <a asp-action="ListaUsr" class="btn btn-secondary">Voltar</a>
        </div>
    </form>
}
else
{
    <p>O utilizador não foi encontrado.</p>
}

Views/Admin/ListaCat.cshtml
@model IEnumerable<HabitAqui.Data.CategoriaHabitacao>

@{
    ViewData["Title"] = "Listagem de Categorias de Habitações";
}

<h2 class="mb-4">Listagem das Categorias de Habitações</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NomeCategoria)
            </th>
            <th>
                Ativo
            </th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NomeCategoria)
                </td>
                <td>
                    @if (item.ativo)
                    {
                        <input type="checkbox" checked disabled />
                    }
                    else
                    {
                        <input type="checkbox" disabled />
                    }
                </td>
                <td>
                    <a asp-action="EditCat" asp-route-id="@item.Id" class="btn btn-primary btn-sm">Editar</a>
                    <a asp-action="DetailsCat" asp-route-id="@item.Id" class="btn btn-secondary btn-sm">Detalhes</a>
                </td>
            </tr>
        }
    </tbody>
</table>

</p>
<div class="btn-group">
    <a asp-action="CreateCat" class="btn btn-success">Adicionar Nova Categoria</a>
    <a asp-area="" asp-controller="Admin" asp-action="Admin" class="btn btn-secondary">Voltar</a>
</div>

Views/Admin/ListaLoc.cshtml
@model IEnumerable<HabitAqui.Data.Locador>

@{
    ViewData["Title"] = "Lista de Locadores";
}
<h2 class="mb-4">Lista de Locadores</h2>
<div class="container mt-4">
    @if (TempData["ErrorMessage"] != null)
    {
        <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
    }
    @if (TempData["SuccessMessage"] != null)
    {
        <div class="alert alert-success">@TempData["SuccessMessage"]</div>
    }

    <form asp-controller="Locadores" asp-action="ListaLoc" method="get">
        <div class="form-group">
            <label for="sortOrder">Ordenar por:</label>
            <div class="btn-group" role="group" aria-label="Ordenar">
                <a class="btn btn-secondary btn-sm" asp-action="ListaLoc" asp-route-sortOrder="@ViewBag.NomeSortParam">Nome ▲▼</a>
                <a class="btn btn-secondary btn-sm" asp-action="ListaLoc" asp-route-sortOrder="@ViewBag.EstadoSortParam">Estado ▲▼</a>
            </div>
        </div>
    </form>

    <table class="table table-striped mt-4">
        <thead class="thead-dark">
            <tr>
                <th class="h6">Nome</th>
                <th class="h6">Estado de Subscrição</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Nome)</td>
                    <td>@Html.DisplayFor(modelItem => item.EstadoSubscricao)</td>
                    <td>
                        <a class="btn btn-primary btn-sm" asp-action="EditLoc" asp-route-id="@item.Id">Editar</a>
                        <a class="btn btn-danger btn-sm" asp-action="DeleteLoc" asp-route-id="@item.Id">Apagar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <div class="mt-4">
        <a class="btn btn-secondary" asp-area="" asp-controller="Admin" asp-action="Admin">Voltar</a>
    </div>
</div>

Views/Admin/ListaUsr.cshtml
@model List<UserViewModel>
@using Microsoft.AspNetCore.Identity

@{
    ViewData["Title"] = "Lista de Utilizadores";
}

<h2 class="mb-4">Lista de utilizadores</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nome de Utilizador</th>
            <th>Email</th>
            <th>Número de Telemóvel</th>
            <th>Estado</th>
            <th>Roles</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.IdUser</td>
                <td>@user.UserName</td>
                <td>@user.Email</td>
                <td>@user.PhoneNumber</td>
                <td>
                    @if (user.inativo)
                    {
                        <span class="text-danger">Inativo</span>
                    }
                    else
                    {
                        <span class="text-success">Ativo</span>
                    }
                </td>
                <td>
                    <span>@string.Join(", ", user.Roles)</span>
                </td>
                <td>

                    <a class="btn btn-sm btn-success" asp-action="Ativar" asp-route-id="@user.IdUser">Ativar</a>
                    <a class="btn btn-sm btn-secondary" asp-action="Inativar" asp-route-id="@user.IdUser">Inativar</a>
                    <a class="btn btn-sm btn-primary" asp-action="EditUsr" asp-route-id="@user.IdUser">Editar</a>
                   
                </td>
            </tr>
        }
    </tbody>
</table>

<div>
    <a class="btn btn-secondary" asp-area="" asp-controller="Admin" asp-action="Admin">Voltar</a>
</div>